### ISSUE TITLE
Impoved readme: The readme is very difficult to undersatnd beause it referes to the open-clip project

### ISSUE THREAD

**Issue by knoriy** [LAION-AI/CLAP#10]
It would be good to have a more concise description of using the codebase.

**Comment by RetroCirce** [comment]
Sure, we will proof the readme in this two weeks, to make the introduction of the readme more clear, by adding some introductions of what each main code file are used for.

**Comment by RetroCirce** [comment]
Hi, we now make the readme file more clear by establishing experiment scripts, examples, paper, appendix and infer examples.
In May the project is still under-research so we did not write the readme. Now you can see an updated  project with milestone .
