### ISSUE TITLE
Sampling rate and pre-trained htsat

### ISSUE THREAD

**Issue by Sreyan88** [LAION-AI/CLAP#114]
Hi,

Thank You for the awesome work. I understand you use this link to download the audio encoder [here](https://drive.google.com/drive/folders/1SMQyzJvc6DwJNuhQ_WI8tlCFL5HG2vk6?usp=sharing), but you train your model on 48,000 with the tiny config.

This [link](https://drive.google.com/drive/folders/1UA8cm3adjLsasY80-dX3kGZ8P3rzGGzk) says that tiny was trained on 32,000 and not 48,000. Are you sure you are using the correct sampling rate for pre-training?

Thank You!

**Comment by RetroCirce** [comment]
I reply it in the [HTS-AT channel](https://github.com/RetroCirce/HTS-Audio-Transformer/issues/44)

**Comment by RetroCirce** [comment]
Also, you can ping me (if you are interning in the same company lol).
