### ISSUE TITLE
Error occurs when using colab to load the pretrained model.

### ISSUE THREAD

**Issue by irena123333** [LAION-AI/CLAP#116]
When I want to load the music_speech_epoch_15_esc_89.25.pt. The error message as below occurs.

RuntimeError                              Traceback (most recent call last)
[<ipython-input-9-5c0714e09360>](https://localhost:8080/#) in <cell line: 2>()
      1 model = laion_clap.CLAP_Module(enable_fusion=False, amodel= 'HTSAT-base')
----> 2 model.load_ckpt('/content/gdrive/MyDrive/CLAP/music_speech_epoch_15_esc_89.25 (1).pt')

1 frames
[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in load_state_dict(self, state_dict, strict)
   2039 
   2040         if len(error_msgs) > 0:
-> 2041             raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
   2042                                self.__class__.__name__, "\n\t".join(error_msgs)))
   2043         return _IncompatibleKeys(missing_keys, unexpected_keys)

RuntimeError: Error(s) in loading state_dict for CLAP:
	Unexpected key(s) in state_dict: "text_branch.embeddings.position_ids".

I run the code in the colab and save the pretrained checkpint in my google drive.
The code I use to load the pretrained model is listed as below.
model = laion_clap.CLAP_Module(enable_fusion=False, amodel= 'HTSAT-base')
model.load_ckpt('/content/gdrive/MyDrive/CLAP/music_speech_epoch_15_esc_89.25 (1).pt')

Can you help me figure out why the error occurs?

**Comment by lukewys** [comment]
Hi, please see https://github.com/LAION-AI/CLAP/issues/113

**Comment by irena123333** [comment]
> Hi, please see #113

Thank you very much! The problem was solved.
