### ISSUE TITLE
[PANN] can i get pann model checkpoints?

### ISSUE THREAD

**Issue by spear011** [LAION-AI/CLAP#124]
Hi and thanks for sharing your awesome project

I'm doing some experiments and I want to test the PANN model, but is it possible to find the checkpoints of the PANN model separately?

Any help would be appreciated.

**Comment by RetroCirce** [comment]
Sure, the PANN model can be found in their original repo: https://github.com/qiuqiangkong/audioset_tagging_cnn

**Comment by spear011** [comment]
thanks!
