### ISSUE TITLE
A bug for obtaining CLAP Embedding

### ISSUE THREAD

**Issue by LittleFlyingSheep** [LAION-AI/CLAP#147]
Hi~I find that in the 49 line of `data/infer_clap.py`, the parameter of the `CLAP_module()` has a wrong name.

The original verision:
```
model = CLAP_Module(enable_fusion=args.enable_fusion, aencoder=args.audio_encoder)
```

In this version, the parameter "aencoder" should be "amodel" according to the library of "laion_clap". Thus, the revised version should be:
```
model = CLAP_Module(enable_fusion=args.enable_fusion, amodel=args.audio_encoder)
```

I hope this suggestion can make this project better.

**Comment by emo-disentanger** [comment]
Thank you for your finding! It is a typo for this version, we will correct it.

**Comment by RetroCirce** [comment]
Thank you for your finding! It is a typo for this version, we will correct it.
