### ISSUE TITLE
Paper request

### ISSUE THREAD

**Issue by liuxubo717** [LAION-AI/CLAP#3]
Do you have a paper (arXiv) for this work?

**Comment by RetroCirce** [comment]
Hi, here it is :)
https://arxiv.org/abs/2211.06687

**Comment by liuxubo717** [comment]
Thanks Ke! Awesome work :)

Best wishes,
Xubo

Knut(Ke) Chen ***@***.***> 于2022年11月16日周三 22:16写道：
