### ISSUE TITLE
Running "zeroshot_esc50.sh"

### ISSUE THREAD

**Issue by swapb94** [LAION-AI/CLAP#52]
How to run the zeroshot evaluation using the pre-trained model provided in the gdrive link?
"eval_retrieval_main.py" requires params.txt, out.log as a part of the log_dir, right? However, only the .pt files have been provided. Is it possible to upload all the contents of the log_dir to gdrive?
Thanks in advance!

**Comment by lukewys** [comment]
Oh, my bad. Thanks for pointing it out!  I will upload them in the near future.

**Comment by lukewys** [comment]
Just updated the google drive folder. Thanks for pointing this out!

**Comment by swapb94** [comment]
What are the contents of "sizes.json"? in esc/train and esc/test
Also, is there a way of running this script without "webdataset"? i.e. using ESC50 on our local system.

**Comment by lukewys** [comment]
Hi Swapnil, We use webdataset as our dataset format. The sizes.json is
related to webdataset format. It records the number of samples for each
tar.

For details of webdataset format we used, you could check
https://github.com/LAION-AI/audio-dataset/ or
https://github.com/webdataset/webdataset. It is possible to train on
webdataset datasets on local storage.

If you want to use the dataset format you want, you could always create a
new type of dataloader and load the data.

Hope this helps.

Best,
Yusong



Swapnil Bhosale ***@***.***> 于2022年11月21日周一 04:06写道：

**Comment by swapb94** [comment]
Got it. Thanks for sharing the links!

**Comment by CoderwayNew** [comment]
I am also try to running "zeroshot_esc50.sh", But I can't find  params.txt, out.log , and epoch_top_0.pt.  I just find some checkpoints like LAION-audio-630K.pt .  Could you please let me know the links to these files ?
Thanks a lot!

**Comment by lukewys** [comment]
Hi @CoderwayNew , we actually have a newer script using the pip API to run the ESC50 zeroshot evaluation, please see: https://github.com/LAION-AI/CLAP/blob/main/experiment_scripts/esc50_api.py
