### ISSUE TITLE
AudioCaps test set size

### ISSUE THREAD

**Issue by kimihailv** [LAION-AI/CLAP#54]
Hello. Could you please specify the size of AudioCaps test set which you used in your evaluation? test.csv file in [audiocaps repo ](https://github.com/cdjkim/audiocaps/tree/master/dataset) contains 4876 rows, but there is also the table with splits' sizes and according to it test set contains 975 samples.

**Comment by lukewys** [comment]
Hi, in audiocaps, there are 5 captions for each audio. So 975*5=4875.

**Comment by kimihailv** [comment]
Thank you
