### ISSUE TITLE
Example of zero-shot evaluation

### ISSUE THREAD

**Issue by andreamad8** [LAION-AI/CLAP#55]
Thanks for the great repo. 

Could you push in the repo a full example of zero-shot evaluation? 

I have been trying with the example you provided, but I am not sure I am providing the right input to the model. Would very useful if you could push a .wav file example in the repo. Would that be possible?

**Comment by lukewys** [comment]
Hi Andrea,

You can find an example of our dataset format in [here](https://drive.google.com/drive/folders/1aU54FGctrjhxA2sTN0wgHVsPm0nPEc_E?usp=share_link).
It contains the full ESC50 dataset, split according to the first 5-fold split.

You should be loading this dataset from your local storage by removing `--remotedata` and add `--datasetpath` pointing to the directory containing the `esc50` folder (`esc50` folder then contains `trian` and `test`)

Hope this helps :)
