### ISSUE TITLE
On the learnable logit_scale parameter

### ISSUE THREAD

**Issue by DaehanKim** [LAION-AI/CLAP#57]
Hi Authors, Thank you deeply for this great work.
While running your codebase, I found the log-logit-scale initialization is a bit different from the original CLIP paper.

In the original paper, they used `np.dot(I_e, T_e.T) * np.exp(t)` with t referring to temperature(=a/t_logit_scale in your implementation). The temperature is initialized with 0.07 according to (Wu et al.,2018). That means multiplied value is (exponential of 0.07) = 1.07.  But In your implementation, it is initialized as 1/0.07 = 14.28, which is quite different from the previous value. (It is first initialized as log(1/0.07) and get exponential to remove log, and multiplied to the dot product matrix. so should be correct)

I wonder whether this is intended. Thank you in advance!

**Comment by lukewys** [comment]
Hi,

If I understand correctly, according to Wu et al 2018
<https://arxiv.org/pdf/1805.01978.pdf> (end of Section 3.4), the
temperature tau is used as $\alpha_i=\exp (s_i \tau)$. Thus, it is used as
a denominator. In the CLIP paper, the "t" in pseudocode "np.dot(I_e, T_e.T)
* np.exp(t)" might not be the tau itself.

Also, this implementation is inherited from open_clip, an opensource
implementation of CLIP.
https://github.com/mlfoundations/open_clip/blob/main/src/open_clip/model.py#L176
.

Although I think the above is the reason for using 1/0.07, I am not 100%
sure about this. Please don't hesitate to raise any further discussion.

Best,
Yusong

DaehanKim ***@***.***> 于2022年12月30日周五 01:13写道：

**Comment by DaehanKim** [comment]
Thank you for the reply. I think you got the point.
