### ISSUE TITLE
RuntimeError: Internal psf_fseek() failed.

### ISSUE THREAD

**Issue by LoieSun** [LAION-AI/CLAP#61]
Hi,
I try to reprocess Clotho and AudioCaps dataset, and calculate the retrieval metrics for audio and text. But when I processed the datas as you released and run the eval code. There is an error, _RuntimeError: Internal psf_fseek() failed._ when I used either Clotho or AudioCaps.

I'm not sure what make this error.

Thank you!

**Comment by RetroCirce** [comment]
Hi,

I guess this is related to the sound file I/O after your machine. What system (linux, mac, window) does you use? 
You can refer this (https://github.com/bastibe/python-soundfile/issues/274) to see if this is related to the flac format reading and libsndfile.
