### ISSUE TITLE
PIP API Update

### ISSUE THREAD

**Issue by lukewys** [LAION-AI/CLAP#81]
@RetroCirce Some features requested for the next update:
1. allow Tensor input for getting audio embedding [is it ok to assign to you @RetroCirce ?]
2. allow gradient in `get_audio_features` for applying classifier-based guidance. [assigned to Yusong]

**Comment by RetroCirce** [comment]
Get it! I will implement the update

**Comment by RetroCirce** [comment]
Already update

**Comment by lukewys** [comment]
Solved. PIP updated
