### ISSUE TITLE
up,I want to know how to tar the dataset to prepare for finetuning?我想知道在finetuning是例如esc50数据集是怎么tar打包的？我用tar -cvf 1.tar fsx 打包之后的数据加载会出现确实’flac‘属性的问题

### ISSUE THREAD

**Issue by wanghua-lei** [LAION-AI/CLAP#87]

**Comment by lukewys** [comment]
Hi, you cannot use the `tar` command provided by the system. You need to make an order-preserving tar (that is, the corresponding text and json for each sample need to be nearby each other in the tar). You can refer to our code to make the tar: https://github.com/LAION-AI/audio-dataset/blob/main/utils/make_tar_utils.py, https://github.com/LAION-AI/audio-dataset/blob/main/utils/make_tar.py

**Comment by wanghua-lei** [comment]
thanks for ans I use command tar -cvf 1.tar fsx/* can solve the problem.
