### ISSUE TITLE
Requirements for more pretrained models

### ISSUE THREAD

**Issue by Ming-er** [LAION-AI/CLAP#91]
Dear authors, thanks for the brilliant work. I wanna know if there are some plans to release more pretrained weights (e.g. PANNS) ?

**Comment by lukewys** [comment]
Hi, we just released three new checkpoints trained using larger model and on larger dataset. Please see: https://github.com/LAION-AI/CLAP#pretrained-models. However, we don't have plans to release models trained on PANNs.

Cheers,
Yusong

**Comment by Ming-er** [comment]
Fine. Anyway, thanks for your work!
